name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - v*
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    name: ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      matrix:
        platform:
         - { name: 'Build (Ubuntu 22.04, x64, release)', os: ubuntu-22.04, build: ./build.sh, architecture: x64, runtime: linux-x64, configuration: release }
         - { name: 'Build (Ubuntu 22.04, x64, debug)', os: ubuntu-22.04, build: ./build.sh, architecture: x64, runtime: linux-x64, configuration: debug }
         - { name: 'Build (Ubuntu 20.04, x64, release)', os: ubuntu-22.04, build: ./build.sh, architecture: x64, runtime: linux-x64, configuration: release }
         - { name: 'Build (Ubuntu 20.04, x64, debug)', os: ubuntu-22.04, build: ./build.sh, architecture: x64, runtime: linux-x64, configuration: debug }
         - { name: 'Build (Windows 2022, x64, release)', os: windows-2022, build: .\build.cmd, architecture: x64, runtime: win-x64, configuration: release }
         - { name: 'Build (Windows 2022, x64, debug)', os: windows-2022, build: .\build.cmd, architecture: x64, runtime: win-x64, configuration: debug }
         - { name: 'Build (Windows 2022, x86, release)', os: windows-2022, build: .\build.cmd, architecture: x86, runtime: win-x86, configuration: release }
         - { name: 'Build (Windows 2022, x86, debug)', os: windows-2022, build: .\build.cmd, architecture: x86, runtime: win-x86, configuration: debug }
         - { name: 'Build (Windows 2019, x64, release)', os: windows-2019, build: .\build.cmd, architecture: x64, runtime: win-x64, configuration: release }
         - { name: 'Build (Windows 2019, x64, debug)', os: windows-2019, build: .\build.cmd, architecture: x64, runtime: win-x64, configuration: debug }
         - { name: 'Build (Windows 2019, x86, release)', os: windows-2019, build: .\build.cmd, architecture: x86, runtime: win-x86, configuration: release }
         - { name: 'Build (Windows 2019, x86, debug)', os: windows-2019, build: .\build.cmd, architecture: x86, runtime: win-x86, configuration: debug }
         - { name: 'Build (MacOS 12, x64, release)', os: macos-12, build: ./build.sh, architecture: x64, runtime: osx-x64, configuration: release }
         - { name: 'Build (MacOS 12, x64, debug)', os: macos-12, build: ./build.sh, architecture: x64, runtime: osx-x64, configuration: debug }
         - { name: 'Build (MacOS 11, x64, release)', os: macos-12, build: ./build.sh, architecture: x64, runtime: osx-x64, configuration: release }
         - { name: 'Build (MacOS 11, x64, debug)', os: macos-12, build: ./build.sh, architecture: x64, runtime: osx-x64, configuration: debug }
    steps:
    - name: Checkout Git Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Restore
      run: >
        ${{ matrix.platform.build }}
        --target restore
        --configuration ${{ matrix.platform.configuration }}
        --architecture ${{ matrix.platform.architecture }}
        --runtime ${{ matrix.platform.runtime }}
    - name: Build
      run: >
        ${{ matrix.platform.build }}
        --target build
        --configuration ${{ matrix.platform.configuration }}
        --architecture ${{ matrix.platform.architecture }}
        --runtime ${{ matrix.platform.runtime }}
    - name: Test
      run: >
        ${{ matrix.platform.build }}
        --target test
        --configuration ${{ matrix.platform.configuration }}
        --architecture ${{ matrix.platform.architecture }}
        --runtime ${{ matrix.platform.runtime }}
